# Commands to start on workspace startup
tasks:
  - name: Setup & Build
    before: npm i -g pnpm
    init: pnpm i
    command: pnpm build

# Ports to expose on workspace startup
ports:
  - port: 5173
    onOpen: open-preview
    name: Website
    description: Website Preview
