name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: deno run -A ./build.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: tsa-webmaster # the name of the project on Deno Deploy
          entrypoint: server.ts # the entrypoint to deploy
