name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: build
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: deno task build-log

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: tsa-webmaster
          entrypoint: server.ts
